export const EN = {
  Menu: {
    Home: "Home",
    SignIn: "SignIn",
    SignUp: "SignUp",
    Messages: "Messages",
    Favorite: "Favorite",
    AddItem: "Add Item",
    Logout: "Logout",
    AboutUs: "About Us",
    PrivacyPolicy: "Privacy Policy",
    Language: "Language",
  },
  Screens: {
    Home: {
      Search: "Search",
      AllCategories: "All Categories",
    },
    SignIn: {
      Username: "Username",
      Password: "Password",
      Login: "Login",
      dontHaveAccount: "Don't Have an Account",
      Create: "Create",
    },
    SignUp: {
      FirstName: "First Name",
      LastName: "Last Name",
      Username: "Username",
      Email: "Email",
      Password: "Password",
      ConfermPass: "Conferm Password",
      Province: "Province",
      SignUp: "SignUp",
      AlreadyHave: "Already Have an Account",
    },
    AddItem: {
      Name: "Name",
      Description: "Description",
      Price: "Price",
      Category: "Category",
      Pick: "Pick An Image",
      PickStorage: "Pick an Image from storage",
      PickCamera: "Pick Image Using camera",
      Country: "Country",
      Phone: "Phone",
      Address: "Address",
      AddItem: "Add Item",
    },
    Product: {
      Name: "Name",
      Price: "Price",
      Category: "Category",
      Address: "Address",
      Phone: "Phone",
      SendMessage: "Send Message",
    },
  },
};

export const FR = {
  Menu: {
    Home: "accueil",
    SignIn: "s'identifier",
    SignUp: "S'inscrire",
    Messages: "Messages",
    Favorite: "Préféré",
    AddItem: "Ajout un item",
    Logout: "Se Déconnecter",
    AboutUs: "À propos de nous",
    PrivacyPolicy: "Politique de confidentialité",
    Language: "Langue",
  },
  Screens: {
    Home: {
      Search: "Rechercher",
      AllCategories: "toutes catégories",
    },
    SignIn: {
      Username: "Nom d'utilisateur",
      Password: "Mot de passe",
      Login: "Connexion",
      dontHaveAccount: "Tu n'as pas de compte",
      Create: "Créer",
    },
    SignUp: {
      FirstName: "Prénom",
      LastName: "Nom de famille",
      Username: "Nom d'utilisateur",
      Email: "E-mail",
      Password: "Mot de passe",
      ConfermPass: "Confirmez le mot de passe",
      Province: "Province",
      SignUp: "S'inscrire",
      AlreadyHave: "J'ai déjà",
    },
    AddItem: {
      Name: "Nom",
      Description: "La description",
      Price: "Prix",
      Category: "Catégorie",
      Pick: "Choisir une Image",
      PickStorage: "Choisir une image dans le stockage",
      PickCamera: "Choisir l'image utiliser l'appareil photo",
      Country: "Pays",
      Phone: "Téléphoner",
      Address: "Adresse",
      AddItem: "Ajouter un item",
    },
    Product: {
      Name: "Nom",
      Price: "Prix",
      Category: "Catégorie",
      Address: "Adresse",
      Phone: "Téléphoner",
      SendMessage: "Envoyer le message",
    },
  },
};

export const ES = {
  Menu: {
    Home: "pagina de inicio",
    SignIn: "Iniciar sesión",
    SignUp: "Inscribirse",
    Messages: "Mensajes",
    Favorite: "favorito",
    AddItem: "añadir artículo",
    Logout: "cerrar sesión",
    AboutUs: "Sobre nosotras",
    PrivacyPolicy: "Politique de confidencialité",
    Language: "Idioma",
  },
  Screens: {
    Home: {
      Search: "Buscar",
      AllCategories: "Todas las categorias",
    },
    SignIn: {
      Username: "Nombre de usuario",
      Password: "Contraseña",
      Login: "Acceso",
      dontHaveAccount: "no tengo cuenta",
    },
    SignUp: {
      FirstName: "Primer nombre",
      LastName: "Apellido",
      Username: "Nombre de usuario",
      Email: "Correo electrónico",
      Password: "Contraseña",
      ConfermPass: "Confirmar pase",
      Province: "Provincia",
      SignUp: "Inscribirse",
      AlreadyHave: "Ya tengo",
    },
    AddItem: {
      Name: "Nom",
      Description: "Descripción",
      Price: "Precio",
      Category: "Categoría",
      Country: "País",
      Pick: "Elige una imagen",
      PickStorage: "Elija una imagen del almacenamiento",
      PickCamera: "Elegir imagen usar cámara",
      Phone: "Teléfono",
      Address: "Habla a",
      AddItem: "Añadir artículo",
    },
    Product: {
      Name: "Nom",
      Price: "Premio",
      Category: "Categoría",
      Address: "Habla a",
      Phone: "Teléfono",
      SendMessage: "Enviar mensaje",
    },
  },
};

export const AR = {
  Menu: {
    Home: "الرئيسية",
    SignIn: "تسجيل دخول",
    SignUp: "تسجيل حساب",
    Messages: "الرسائل",
    Favorite: "المفضلة",
    AddItem: "اضافة اعلان",
    Logout: "تسجيل الخروج",
    AboutUs: "نبذة عنا",
    PrivacyPolicy: "سياسة الخصوصية",
    Language: "لغة",
  },
  Screens: {
    Home: {
      Search: "بحث",
      AllCategories: "جميع الأقسام",
    },
    SignIn: {
      Username: "اسم المستخدم",
      Password: "كلمة المرور",
      Login: "دخول",
      dontHaveAccount: "لا تملك اي حساب",
      Create: "انشاء",
    },
    SignUp: {
      FirstName: "الاسم الاول",
      LastName: "الاسم الثاني",
      Username: "اسم المستخدم",
      Email: "البريد الالكتروني",
      Password: "كلمة المرور",
      ConfermPass: "تأكيد كلمة المرور",
      Province: "المحافظة",
      SignUp: "تسجيل",
      AlreadyHave: "لديك حساب سابقا",
    },
    AddItem: {
      Name: "اسم",
      Description: "الوصف",
      Price: "السعر",
      Category: "القسم",
      Pick: "ارفع صورة",
      PickStorage: "ارفع صورة من المعرض",
      PickCamera: "ارفع صورة باستعمال الكاميرا",
      Country: "الدولة",
      Phone: "الهاتف",
      Address: "العنوان",
      AddItem: "اضافة عنصر",
    },
    Product: {
      Name: "الاسم",
      Price: "السعر",
      Category: "القسم",
      Address: "العنوان",
      Phone: "الهاتف",
      SendMessage: "ارسل رسالة",
    },
  },
};

export const HI = {
  Menu: {
    Home: "घर",
    SignIn: "दाखिल करना",
    SignUp: "साइन अप करें",
    Messages: "संदेशों",
    Favorite: "पसंदीदा",
    AddItem: "सामान जोडें",
    Logout: "लॉग आउट",
    AboutUs: "हमारे बारे में",
    PrivacyPolicy: "गोपनीयता नीति",
    Language: "भाषा",
  },
  Screens: {
    Home: {
      Search: "खोज",
      AllCategories: "सब वर्ग",
    },
    SignIn: {
      Username: "उपयोगकर्ता नाम",
      Password: "कुंजिका",
      Login: "लॉग इन करें",
      dontHaveAccount: "खाता नहीं है",
      Create: "बनाएं",
    },
    SignUp: {
      FirstName: "नाम",
      LastName: "उपनाम",
      Username: "उपयोगकर्ता नाम",
      Email: "ईमेल",
      Password: "कुंजिका",
      ConfermPass: "पासवर्ड की पुष्टि कीजिये",
      Province: "प्रांत",
      SignUp: "साइन अप करें",
      AlreadyHave: "पहले से ही एक खाता है",
    },
    AddItem: {
      Name: "नाम",
      Description: "विवरण",
      Price: "कीमत",
      Category: "श्रेणी",
      Pick: "एक छवि चुनें",
      PickStorage: "भंडारण से एक छवि चुनें",
      PickCamera: "कैमरे का उपयोग करके छवि चुनें",
      Country: "देश",
      Phone: "फ़ोन",
      Address: "पता",
      AddItem: "सामान जोडें",
    },
    Product: {
      Name: "नाम",
      Price: "कीमत",
      Category: "श्रेणी",
      Address: "पता",
      Phone: "फ़ोन",
      SendMessage: "मेसेज भेजें",
    },
  },
};

export const CH = {
  Menu: {
    Home: "家",
    SignIn: "登入",
    SignUp: "报名",
    Messages: "留言",
    Favorite: "最喜欢的",
    AddItem: "添加项目",
    Logout: "登出",
    AboutUs: "关于我们",
    PrivacyPolicy: "隐私政策",
    Language: "语",
  },
  Screens: {
    Home: {
      Search: "搜索",
      AllCategories: "所有类别",
    },
    SignIn: {
      Username: "用户名",
      Password: "密码",
      Login: "登录",
      dontHaveAccount: "没有账户",
      Create: "创建",
    },
    SignUp: {
      FirstName: "名",
      LastName: "姓",
      Username: "用户名",
      Email: "电子邮件",
      Password: "密码",
      ConfermPass: "确认密码",
      Province: "省",
      SignUp: "报名",
      AlreadyHave: "已有账号",
    },
    AddItem: {
      Name: "名称",
      Description: "描述",
      Price: "价钱",
      Category: "类别",
      Pick: "选择图像",
      PickStorage: "从存储中选择图像",
      PickCamera: "使用相机拾取图像",
      Country: "国家",
      Phone: "电话",
      Address: "地址",
      AddItem: "添加项目",
    },
    Product: {
      Name: "名称",
      Price: "价钱",
      Category: "类别",
      Address: "地址",
      Phone: "电话",
      SendMessage: "发信息",
    },
  },
};
